spring:
  application:
    name: collector

## не получается подлючить конфигурацию через application
collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: telemetry.collector
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: kafka.serializer.GeneralAvroSerializer
      topics:
        sensors-events: telemetry.sensors.v1
        hub-events: telemetry.hubs.v1
