CREATE TABLE IF NOT EXISTS shopping_carts (
    shopping_cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR NOT NULL,
    is_activated BOOLEAN NOT NULL,
    CONSTRAINT shopping_carts
       PRIMARY KEY (shopping_cart_id)
);


CREATE TABLE IF NOT EXISTS carts_products (
    shopping_cart_id BIGINT NOT NULL,
    product_id VARCHAR NOT NULL,
    quantity BIGINT NOT NULL,
    CONSTRAINT carts_products_PK
        PRIMARY KEY (shopping_cart_id, product_id),
    CONSTRAINT FK_SHOPPING_CART_CARTS_PRODUCTS
                                          FOREIGN KEY (shopping_cart_id)
                                          REFERENCES shopping_carts (shopping_cart_id)
                                          ON DELETE CASCADE
)

