spring:
  application:
    name: warehouse
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
  datasource:
    username: "main"
    password: "main"
    url: jdbc:postgresql://localhost:9435/postgres
    driver-class-name: "org.postgresql.Driver"

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/