-- CREATE TABLE IF NOT EXISTS categories (
--                                       category_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
--                                       name VARCHAR
-- );
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE IF NOT EXISTS products (
    product_id VARCHAR PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    image_src VARCHAR,
    quantity_state VARCHAR,
    product_state VARCHAR,
    rating FLOAT,
    category VARCHAR,
    price FLOAT

--     CONSTRAINT PRODUCTS_CATEGORY_ID_FK_CATEGORIES_CATEGORY_ID
--         FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE RESTRICT

);

